#!/bin/bash
########################################################################
#  Project Magpie. For details, see https://github.com/llnl/magpie.
#
#  Copyright (C) 2019 Intel Corporation. All rights reserved.
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License version
#  2 as published by the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  Aleksander Kantak <aleksander.kantak@intel.com>
########################################################################

source ${MAGPIE_SCRIPTS_HOME}/magpie/lib/magpie-lib-log

Magpie_run_start_tensorflow_horovod () {

    if [ "${TENSORFLOW_HOROVOD_SETUP}" != "yes" ]
    then
        magpie_run_tensorflow_horovod_should_be_torndown=0
        magpie_run_tensorflow_horovod_setup_successful=1
        return 0
    fi

    magpie_run_tensorflow_horovod_should_be_torndown=1
    magpie_run_tensorflow_horovod_setup_successful=1
    return 0
}

Magpie_run_tensorflow_horovod () {

    TENSORFLOW_HOROVOD_EXECUTABLE=""

    if [ "${TENSORFLOW_HOROVOD_JOB}" == "cnn-benchmark" ]
    then

        TENSORFLOW_HOROVOD_EXECUTABLE="${MAGPIE_SCRIPTS_HOME}/magpie/job/magpie-job-tensorflow-horovod-cnn-benchmark"

    elif [ "${TENSORFLOW_HOROVOD_JOB}" == "synthetic-benchmark" ]
    then

        TENSORFLOW_HOROVOD_EXECUTABLE="${MAGPIE_SCRIPTS_HOME}/magpie/job/magpie-job-tensorflow-horovod-synthetic-benchmark"

    elif [ "${TENSORFLOW_HOROVOD_JOB}" == "script" ]
    then

        TENSORFLOW_HOROVOD_EXECUTABLE=${TENSORFLOW_HOROVOD_SCRIPT_PATH}

    else

        Magpie_output_internal_error "TENSORFLOW_HOROVOD_JOB = ${TENSORFLOW_HOROVOD_JOB} not handled"

    fi

    # run selected executable and wait
    ${MAGPIE_SCRIPTS_HOME}/magpie/run/magpie-run-execute script ${TENSORFLOW_HOROVOD_EXECUTABLE} &
    local scriptpid=$!
    Magpie_wait_script_sigusr2_on_job_timeout ${scriptpid}

}

Magpie_teardown_tensorflow_horovod () {

    if [ "${magpie_run_tensorflow_horovod_should_be_torndown}" == "1" ]
    then
        magpie_run_tensorflow_horovod_teardown_complete=1
    fi
}
